//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace NativeXtraReportExample.Module.BusinessObjects {
  [DefaultClassOptions]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Task")]
  [DevExpress.ExpressApp.DC.XafDefaultPropertyAttribute("Subject")]
  public partial class Task : DevExpress.Persistent.BaseImpl.BaseObject {
    private System.DateTime _deadline;
    private System.String _description;
    private System.String _subject;
    public Task(DevExpress.Xpo.Session session)
      : base(session) {
    }
    public System.String Subject {
      get {
        return _subject;
      }
      set {
        SetPropertyValue("Subject", ref _subject, value);
      }
    }
    public System.DateTime Deadline {
      get {
        return _deadline;
      }
      set {
        SetPropertyValue("Deadline", ref _deadline, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(-1)]
    public System.String Description {
      get {
        return _description;
      }
      set {
        SetPropertyValue("Description", ref _description, value);
      }
    }
  }
}
